name: Metrics
on: [push]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_METRICS }}
          filename: assets/metrics.classic.svg
          base: header, repositories
          template: classic
